#!/bin/bash

# Useful func
pda_usage() { err "Missing args\n\nUsage:"; usage 2>/dev/null ||
              echo -e "    $0 <dashed args>"; }
err() { echo -e "$@"; PDA_EXIT_CODE=1; }
die() { err "\n$@\n"; exit 1; }
perr() { err "PDA: Error parsing arg: '$@'"; }

pda() {
  [ -n "$1" ] || pda_usage
  PDA_EXIT_CODE=0

  # Debugging
  if [ -n "$PDA_DEBUG" ]; then
      echo "PDA: Parsing dashed args: $@"
      print_var() { echo "PDA: Setting $1 to '${!1}'"; }
  else
      print_var() { :; }
  fi

  # Parse loop
  while  (( "$#" )); do
      flag=0

      # Var
      var=$1; shift
      if ! [[ "$var" =~ ^'--'* ]]; then perr "$var"; break; fi
      var=${var#--}
      # Val
      if [ "$1" == "" ] || [[ "$1" =~ ^'--'* ]]; then
          val=1; flag=1
      else
          val="$1"; shift
      fi
      read ${var} &>/dev/null <<< "$val"
      if [ $? -ne 0 ]; then
        [ "$flag" == 1 ] && perr "--$var" || perr "--$var $val"
        break
      fi
      print_var $var
  done

  return $PDA_EXIT_CODE
}
